include: package:lint/analysis_options.yaml

analyzer:
    strong-mode:
        # https://www.dartlang.org/guides/language/analysis-options#enabling-additional-type-checks
    exclude:
        - "**/*.g.dart"
        - "**/*.gr.dart"
        - "**/*.freezed.dart"
        - lib/**/*.g.dart
        - lib/**/*.model.dart

    errors:
        invalid_annotation_target: ignore
        missing_required_param: error
        # treat missing returns as a warning (not a hint)
        missing_return: warning
        # allow having TODOs in the code
        todo: ignore
linter:
    rules:
        sort_pub_dependencies: false
        depend_on_referenced_packages: false
        use_super_parameters: true
        constant_identifier_names: false
        directives_ordering: false
        # Disable this rule because import components with relative imports
        always_use_package_imports: false
